require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'examples/**/*'
    - 'spec/fixtures/**/*'
    - 'vendor/bundle/**/*'

Metrics/BlockLength:
  Exclude:
    - Rakefile

Style/StringLiterals:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleWithoutDescription:
  EnforcedStyle: single_line_only

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

FactoryBot/FactoryAssociationWithStrategy:
  Enabled: false
